let adminPassword='';
const H=()=>({'Content-Type':'application/json','x-admin-password':adminPassword});
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{...(opt.headers||{}),...H()}});const j=await r.json();if(!j.ok)throw new Error(j.error||'Errore');return j}
function applyTheme(s={}){document.documentElement.setAttribute('data-theme',s.theme||localStorage.theme||'clean-light'); if(s.theme)localStorage.theme=s.theme; if(s.logo_text) sideLogo.textContent=s.logo_text; if(s.gym_name){dashGymName.textContent=s.gym_name; sideName.innerHTML=s.gym_name.replace(' ','<br>')}}
async function login(){adminPassword=document.getElementById('adminPass').value;try{await api('/api/admin/login',{method:'POST'});document.getElementById('login').style.display='none';document.getElementById('app').style.display='flex';await loadSettings(false);loadDashboard()}catch(e){loginMsg.textContent=e.message}}
function show(id,btn){document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));btn?.classList.add('active');title.textContent=btn?.textContent||'Admin'}
async function loadDashboard(){const j=await api('/api/admin/dashboard');sCustomers.textContent=j.stats.customers;sCards.textContent=j.stats.activeCards;sExpiring.textContent=j.stats.expiringSoon;sDenied.textContent=j.stats.deniedToday}
async function loadCustomers(){const j=await api('/api/admin/customers');customersBody.innerHTML=j.customers.map(c=>`<tr><td>${c.member_code}</td><td>${c.full_name}</td><td>${c.card_code||''}</td><td>${c.nfc_serial||''}</td><td>${c.access_level||'member'}</td><td>${c.valid_until||''}</td><td>${c.revoked?'Revocato':(c.card_status||'')}</td><td><button class="danger" onclick="revoke(${c.id},${c.revoked?0:1})">${c.revoked?'Riattiva':'Revoca'}</button></td></tr>`).join('')}
async function createCustomer(){const body={memberCode:memberCode.value,fullName:fullName.value,phone:phone.value,email:email.value,address:address.value,cardCode:cardCode.value,nfcSerial:nfcSerial.value,accessLevel:accessLevel.value,memberSince:memberSince.value,validUntil:validUntil.value,medicalCertificateExpiry:medicalCertificateExpiry.value,regulationSigned:regulationSigned.checked};try{await api('/api/admin/customers',{method:'POST',body:JSON.stringify(body)});newCustomerMsg.textContent='Cliente creato';document.querySelectorAll('#newCustomer input').forEach(i=>{if(i.type==='checkbox')i.checked=false;else i.value=''})}catch(e){newCustomerMsg.textContent=e.message}}
async function revoke(id,val){await api('/api/admin/revoke',{method:'POST',body:JSON.stringify({customerId:id,revoked:val,reason:val?'Revoca manuale admin':'Riattivazione admin'})});loadCustomers()}
async function loadPrices(){const j=await api('/api/admin/prices');pricesBody.innerHTML=j.prices.map(p=>`<tr><td>${p.code}</td><td>${p.label}</td><td>${p.days}</td><td>€ ${Number(p.price).toFixed(2)}</td></tr>`).join('')}
async function savePrice(){await api('/api/admin/prices',{method:'POST',body:JSON.stringify({code:pCode.value,label:pLabel.value,days:Number(pDays.value),price:Number(pPrice.value),enabled:1})});loadPrices()}
async function loadOperators(){const j=await api('/api/admin/operators');operatorsBody.innerHTML=j.operators.map(o=>`<tr><td>${o.username}</td><td>${o.display_name}</td><td>${o.role}</td><td>${o.active?'Sì':'No'}</td></tr>`).join('')}
async function createOperator(){await api('/api/admin/operators',{method:'POST',body:JSON.stringify({username:opUser.value,displayName:opName.value,password:opPass.value,role:opRole.value})});loadOperators()}
async function loadPayments(){const j=await api('/api/admin/payments');paymentsBody.innerHTML=j.payments.map(p=>`<tr><td>${p.created_at}</td><td>${p.customer_id}</td><td>${p.price_code}</td><td>€ ${Number(p.amount).toFixed(2)}</td><td>${p.new_expiry}</td><td>${p.ip||''}</td></tr>`).join('')}
async function loadLogs(){const j=await api('/api/admin/logs');accessLogsBody.innerHTML=j.accessLogs.map(l=>`<tr><td>${l.created_at}</td><td>${l.card_code||l.nfc_serial}</td><td>${l.result}</td><td>${l.reason||''}</td><td>${l.device_id||''}</td></tr>`).join('');adminLogsBody.innerHTML=j.adminLogs.map(l=>`<tr><td>${l.created_at}</td><td>${l.username||''}</td><td>${l.action}</td><td>${l.ip||''}</td></tr>`).join('')}
async function loadCleaning(){const j=await api('/api/admin/cleaning-diary');cleaningBody.innerHTML=j.entries.map(e=>`<tr><td>${e.created_at}</td><td>${e.card_code||''}</td><td>${e.nfc_serial||''}</td><td>${e.device_id||''}</td><td>${e.note||''}</td></tr>`).join('')}
function setThemeChoice(t){setTheme.value=t;applyTheme({theme:t})}
async function loadSettings(fill=true){const j=await api('/api/admin/settings');const s=j.settings;applyTheme(s); if(!fill)return; setGymName.value=s.gym_name||'';setLogoText.value=s.logo_text||'PG';setTheme.value=s.theme||'clean-light';setOpenSeconds.value=s.open_seconds||5;setAntiPassback.value=s.anti_passback_seconds||60;setFrom.value=s.allowed_from||'06:00';setTo.value=s.allowed_to||'23:00';setMaxDaily.value=s.max_daily_accesses||0;setPublicMessage.value=s.public_message||''}
async function saveSettings(){const body={gym_name:setGymName.value,logo_text:setLogoText.value,theme:setTheme.value,open_seconds:setOpenSeconds.value,anti_passback_seconds:setAntiPassback.value,allowed_from:setFrom.value,allowed_to:setTo.value,max_daily_accesses:setMaxDaily.value,public_message:setPublicMessage.value};await api('/api/admin/settings',{method:'POST',body:JSON.stringify(body)});applyTheme(body);settingsMsg.textContent='Impostazioni salvate'}
async function backup(){const j=await api('/api/admin/backup',{method:'POST'});alert('Backup creato: '+j.file)}
document.documentElement.setAttribute('data-theme',localStorage.theme||'clean-light');
